<?php

namespace ContainerAw94365;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGalerieControllersupprimerPhotoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6L.aIHC.App\Controller\GalerieController::supprimerPhoto()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6L.aIHC.App\\Controller\\GalerieController::supprimerPhoto()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'photo' => ['privates', '.errored..service_locator.6L.aIHC.App\\Entity\\Photo', NULL, 'Cannot autowire service ".service_locator.6L.aIHC": it needs an instance of "App\\Entity\\Photo" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'photo' => 'App\\Entity\\Photo',
            'em' => '?',
        ]))->withContext('App\\Controller\\GalerieController::supprimerPhoto()', $container);
    }
}
