<?php

namespace ContainerAw94365;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurityControllerunlockUserService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TQe_LeF.App\Controller\SecurityController::unlockUser()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TQe_LeF.App\\Controller\\SecurityController::unlockUser()'] = ($container->privates['.service_locator.TQe_LeF'] ?? $container->load('get_ServiceLocator_TQeLeFService'))->withContext('App\\Controller\\SecurityController::unlockUser()', $container);
    }
}
