<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'galerie' => [[], ['_controller' => 'App\\Controller\\GalerieController::galerie'], [], [['text', '/galerie']], [], [], []],
    'galerie_ajouter' => [[], ['_controller' => 'App\\Controller\\GalerieController::ajouterPhoto'], [], [['text', '/galerie/ajouter']], [], [], []],
    'galerie_supprimer' => [['id'], ['_controller' => 'App\\Controller\\GalerieController::supprimerPhoto'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/galerie/supprimer']], [], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
    'admin_users' => [[], ['_controller' => 'App\\Controller\\SecurityController::adminUsers'], [], [['text', '/admin/users']], [], [], []],
    'admin_user_delete' => [['id'], ['_controller' => 'App\\Controller\\SecurityController::deleteUser'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/user/delete']], [], [], []],
    'admin_user_unlock' => [['id'], ['_controller' => 'App\\Controller\\SecurityController::unlockUser'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/user/unlock']], [], [], []],
    'App\Controller\GalerieController::galerie' => [[], ['_controller' => 'App\\Controller\\GalerieController::galerie'], [], [['text', '/galerie']], [], [], []],
    'App\Controller\GalerieController::ajouterPhoto' => [[], ['_controller' => 'App\\Controller\\GalerieController::ajouterPhoto'], [], [['text', '/galerie/ajouter']], [], [], []],
    'App\Controller\GalerieController::supprimerPhoto' => [['id'], ['_controller' => 'App\\Controller\\GalerieController::supprimerPhoto'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/galerie/supprimer']], [], [], []],
    'App\Controller\HomeController::index' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'App\Controller\RegistrationController::register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'App\Controller\SecurityController::login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'App\Controller\SecurityController::logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
    'App\Controller\SecurityController::adminUsers' => [[], ['_controller' => 'App\\Controller\\SecurityController::adminUsers'], [], [['text', '/admin/users']], [], [], []],
    'App\Controller\SecurityController::deleteUser' => [['id'], ['_controller' => 'App\\Controller\\SecurityController::deleteUser'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/user/delete']], [], [], []],
    'App\Controller\SecurityController::unlockUser' => [['id'], ['_controller' => 'App\\Controller\\SecurityController::unlockUser'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/user/unlock']], [], [], []],
];
