<?php

namespace Container5hqxuea;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FECd9gxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FECd9gx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FECd9gx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\GalerieController::galerie' => ['privates', '.service_locator.TWxDQA4.App\\Controller\\GalerieController::galerie()', 'getGalerieControllergalerieService', true],
            'App\\Controller\\GalerieController::ajouterPhoto' => ['privates', '.service_locator.TWxDQA4.App\\Controller\\GalerieController::ajouterPhoto()', 'getGalerieControllerajouterPhotoService', true],
            'App\\Controller\\GalerieController::supprimerPhoto' => ['privates', '.service_locator.6L.aIHC.App\\Controller\\GalerieController::supprimerPhoto()', 'getGalerieControllersupprimerPhotoService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.k10ghGs.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.nT8jqMP.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\SecurityController::adminUsers' => ['privates', '.service_locator.TWxDQA4.App\\Controller\\SecurityController::adminUsers()', 'getSecurityControlleradminUsersService', true],
            'App\\Controller\\SecurityController::deleteUser' => ['privates', '.service_locator.TQe_LeF.App\\Controller\\SecurityController::deleteUser()', 'getSecurityControllerdeleteUserService', true],
            'App\\Controller\\SecurityController::unlockUser' => ['privates', '.service_locator.TQe_LeF.App\\Controller\\SecurityController::unlockUser()', 'getSecurityControllerunlockUserService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\GalerieController:galerie' => ['privates', '.service_locator.TWxDQA4.App\\Controller\\GalerieController::galerie()', 'getGalerieControllergalerieService', true],
            'App\\Controller\\GalerieController:ajouterPhoto' => ['privates', '.service_locator.TWxDQA4.App\\Controller\\GalerieController::ajouterPhoto()', 'getGalerieControllerajouterPhotoService', true],
            'App\\Controller\\GalerieController:supprimerPhoto' => ['privates', '.service_locator.6L.aIHC.App\\Controller\\GalerieController::supprimerPhoto()', 'getGalerieControllersupprimerPhotoService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.k10ghGs.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.nT8jqMP.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\SecurityController:adminUsers' => ['privates', '.service_locator.TWxDQA4.App\\Controller\\SecurityController::adminUsers()', 'getSecurityControlleradminUsersService', true],
            'App\\Controller\\SecurityController:deleteUser' => ['privates', '.service_locator.TQe_LeF.App\\Controller\\SecurityController::deleteUser()', 'getSecurityControllerdeleteUserService', true],
            'App\\Controller\\SecurityController:unlockUser' => ['privates', '.service_locator.TQe_LeF.App\\Controller\\SecurityController::unlockUser()', 'getSecurityControllerunlockUserService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\GalerieController::galerie' => '?',
            'App\\Controller\\GalerieController::ajouterPhoto' => '?',
            'App\\Controller\\GalerieController::supprimerPhoto' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\SecurityController::adminUsers' => '?',
            'App\\Controller\\SecurityController::deleteUser' => '?',
            'App\\Controller\\SecurityController::unlockUser' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\GalerieController:galerie' => '?',
            'App\\Controller\\GalerieController:ajouterPhoto' => '?',
            'App\\Controller\\GalerieController:supprimerPhoto' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\SecurityController:adminUsers' => '?',
            'App\\Controller\\SecurityController:deleteUser' => '?',
            'App\\Controller\\SecurityController:unlockUser' => '?',
        ]);
    }
}
