<?php

namespace Container5hqxuea;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPhotoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.6L.aIHC.App\Entity\Photo' shared service.
     *
     * @return \App\Entity\Photo
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.6L.aIHC": it needs an instance of "App\\Entity\\Photo" but this type has been excluded in "config/services.yaml".');
    }
}
